name: SlideJot
options:
  bundleIdPrefix: com.slidejot
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
  generateEmptyDirectories: true

settings:
  base:
    SWIFT_VERSION: "5.9"
    MARKETING_VERSION: "1.0.0"
    CURRENT_PROJECT_VERSION: "1"

packages:
  GRDB:
    url: https://github.com/groue/GRDB.swift
    from: "6.24.0"

targets:
  SlideJot:
    type: application
    platform: iOS
    sources:
      - path: SlideJot/Sources
      - path: SlideJot/Resources
    dependencies:
      - package: GRDB
    settings:
      base:
        INFOPLIST_FILE: SlideJot/Info.plist
        PRODUCT_BUNDLE_IDENTIFIER: com.slidejot.ios
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        CODE_SIGN_ENTITLEMENTS: SlideJot/SlideJot.entitlements
    entitlements:
      path: SlideJot/SlideJot.entitlements
      properties:
        com.apple.developer.icloud-container-identifiers:
          - iCloud.com.slidejot.ios
        com.apple.developer.icloud-services:
          - CloudDocuments
        com.apple.developer.ubiquity-container-identifiers:
          - iCloud.com.slidejot.ios
